mongodb:
  architecture: standalone
  useStatefulSet: true
  replicaCount: 1

  image:
    tag: 4.2.12-debian-10-r41

  auth:
    rootPassword: "simple-root-password"

  persistence:
    enabled: true
    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    ## Ignored when mongodb.architecture=replicaset
    ##
    # existingClaim:
    ## PV Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ## set, choosing the default provisioner.
    ##
    # storageClass: "-"
    ## PV Access Mode
    ##
    accessModes:
      - ReadWriteOnce
    ## PVC size
    ##
    size: 20Gi
    ## PVC annotations
    ##
#     annotations: {
# #      volume.beta.kubernetes.io/storage-class: "mongo-ebs"
#     }
    ## The path the volume will be mounted at, useful when using different
    ## MongoDB(R) images.
    ##
    # mountPath: /bitnami/mongodb
    ## The subdirectory of the volume to mount to, useful in dev environments
    ## and one PV for multiple services.
    ##
    # subPath: ""
    ## Fine tuning for volumeClaimTemplates
    ##
    # volumeClaimTemplates:
      ## A label query over volumes to consider for binding (e.g. when using local volumes)
      ## See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#labelselector-v1-meta for more details
      ##
#      selector:
#        matchLabels:
#          name: mongo-ebs

